# Generated by Django 4.2.13 on 2025-01-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_fileshedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Стафф'),
        ),
    ]
