# Generated by Django 4.2.13 on 2025-01-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileschedule',
            name='file_url',
            field=models.URLField(null=True, verbose_name='Ссылка на файл'),
        ),
    ]
