# Generated by Django 4.2.13 on 2025-01-26 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_fileschedule_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='audience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.audience', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.type', verbose_name='Тип'),
        ),
    ]
