# Generated by Django 4.2.13 on 2025-01-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_lesson_audience_alter_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repetition',
            name='name_repetition',
            field=models.CharField(max_length=100, verbose_name='Регулярность'),
        ),
    ]
