# Generated by Django 4.2.13 on 2025-01-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_repetition_name_repetition'),
    ]

    operations = [
        migrations.AddField(
            model_name='repetition',
            name='repetition_reduction',
            field=models.CharField(default='не указано', max_length=100, verbose_name='Сокращение'),
            preserve_default=False,
        ),
    ]
